In [4]:
import numpy as np
a=np.array([3,4,5])
b=np.array([1,0,8])
C=np.dot(a,b)
print(C)
D=np.inner(a,b)
print(D)

43
43


In [19]:
import numpy as np
a=np.array([[2,3,4], [1,2,4],[0,4,9]])
b=np.array([[1,2],[2,0],[9,10]])
c=np.dot(a,b)
print(c)
D=np.matmul(a,b)
print(D)

[[44 44]
 [41 42]
 [89 90]]
[[44 44]
 [41 42]
 [89 90]]


In [20]:
import numpy as np
a=np.array([[2,4,5],[4,6,7]])
D=np.linalg.norm(a)
print(D)


12.083045973594572


In [21]:
import numpy as np
a=np.array([3,4,5])
b=np.array([1,0,8])
C=np.dot(a,b)
D=np.linalg.norm(a)
V=np.linalg.norm(b)
K=D*V
cosA=C/K
print(cosA)

0.7542698966040451


In [46]:
import numpy as np
A = np.matrix('0 -1; 10 4')
print(A)
d = np.linalg.det(A)
print(d)
j=np.around(d)
print(j)
b=A.T
print(b)
g=np.linalg.det(b)
print(g)
n=np.around(g)
print(n)
A[[0,0]]=0
D=np.linalg.det(A)
print(D)
B=np.matrix('1 12;9 5')
B[[1,0]]=B[[0,1]]
print(B)
N=np.linalg.det(B)
print(N)
O=np.matrix('1 3;1 3')
print(np.linalg.det(O))
O[0]=O[0]*2
print(np.linalg.det(O))
P = np.matrix('0 5; 10 14')
P[1]=P[1]+P[0]*3
print(np.linalg.det(P))

[[ 0 -1]
 [10  4]]
10.000000000000002
10.0
[[ 0 10]
 [-1  4]]
10.000000000000002
10.0
0.0
[[ 9  5]
 [ 1 12]]
103.00000000000001
0.0
0.0
-50.000000000000014
